### ISSUE TITLE
Won't play on Windows 10

### ISSUE THREAD

**Issue by kasteiner** [YoungNeer/fruit-crush#1]
Error

lib/clove.lua:220: Clove Error! Directory 'assets/graphics\gameBackground.png' doesn't exist!

Traceback

[C]: in function 'assert'
lib/clove.lua:220: in function 'load'
lib/clove.lua:248: in function 'loadImages'
src/util.lua:2: in main chunk
[C]: in function 'require'
main.lua:1: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by besnoi** [comment]
Sorry about that - the [latest commit](https://github.com/YoungNeer/fruit-crush/commit/c45b42b70a8f7319d27067efae1bca17a3281478) takes care of the problem i believe!

**Comment by kasteiner** [comment]
There is another bug sadly 
```
Error

lib/iffy.lua:167: attempt to index local 'infile' (a nil value)


Traceback

lib/iffy.lua:167: in function 'newAtlas'
src/util.lua:24: in main chunk
[C]: in function 'require'
main.lua:1: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

**Comment by besnoi** [comment]
thanks for pointing it out! I forgot to use the updated version of iffy in fruit-crush! I do hope the [latest](https://github.com/YoungNeer/fruit-crush/commit/8cb378a32cb00e402b2c01fa3e4842c0f0a37691) commit should fix this!

**Comment by kasteiner** [comment]
Now I can access the game however after 2 rounds I get this 

`Error

lib/euler.lua:16: bad argument #1 to 'Max' (number expected, got nil)


Traceback

[C]: in function 'Max'
lib/euler.lua:16: in function 'constrain'
src/Entities/ScoreBoard.lua:7: in function 'init'
lib/Class.lua:79: in function 'ScoreBoard'
src/Scenes/RoundOverState.lua:5: in function 'enter'
src/StateMachine.lua:25: in function 'switch'
src/Scenes/PlayState.lua:132: in function '_oncomplete'
lib/flux.lua:174: in function 'update'
src/Scenes/RoundOverState.lua:40: in function <src/Scenes/RoundOverState.lua:39>
src/StateMachine.lua:38: in function 'update'
main.lua:8: in function 'update'
[C]: in function 'xpcall'`

**Comment by besnoi** [comment]
Yeah that's a bug in the level-generator algorithm! I'm sorry but I can do nothing about it (as i lost interest in the project and am currently working on some other thing)! I'd however love if someone can come up with a fix and make a PR on that!
(again sorry for being lazy here) :>

**Comment by besnoi** [comment]
Issue SOLVED! 

In this [commit](https://github.com/YoungNeer/fruit-crush/commit/d817bb58b5c4d627725b3526294fb8007f51d5a5)!

The problem was that I forgot to add a End Game State, which looks like [this](https://github.com/YoungNeer/fruit-crush/blob/master/screenshots/loseScreen.png).

Hopefully everything should be solved now @kasteiner!
